; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -O3 -mtriple=x86_64-linux-gnu -mcpu=c86-4g-m7 | FileCheck %s --check-prefixes=CHENGDU-DEFAULT
; RUN: llc < %s -O3 -mtriple=x86_64-linux-gnu -mcpu=c86-4g-m7 -x86-constpool-vec-load-opt=false | FileCheck %s --check-prefixes=CHENGDU-DISABLE-OPT

define dso_local void @test_broadcast_generation(ptr nocapture noundef writeonly %0, ptr nocapture noundef writeonly %1, ptr nocapture noundef readonly %2) local_unnamed_addr {
; CHENGDU-DEFAULT-LABEL: test_broadcast_generation:
; CHENGDU-DEFAULT:       # %bb.0:
; CHENGDU-DEFAULT-NEXT:    vmovupd {{.*#+}} ymm0 = [3.1415926535897931E+0,3.1415926535897931E+0,3.1415926535897931E+0,3.1415926535897931E+0]
; CHENGDU-DEFAULT-NEXT:    vaddpd (%rdx), %ymm0, %ymm1
; CHENGDU-DEFAULT-NEXT:    vmulpd 32(%rdx), %ymm0, %ymm0
; CHENGDU-DEFAULT-NEXT:    vmovupd %ymm1, (%rdi)
; CHENGDU-DEFAULT-NEXT:    vmovupd %ymm0, (%rsi)
; CHENGDU-DEFAULT-NEXT:    vzeroupper
; CHENGDU-DEFAULT-NEXT:    retq
;
; CHENGDU-DISABLE-OPT-LABEL: test_broadcast_generation:
; CHENGDU-DISABLE-OPT:       # %bb.0:
; CHENGDU-DISABLE-OPT-NEXT:    vbroadcastsd {{.*#+}} ymm0 = [3.1415926535897931E+0,3.1415926535897931E+0,3.1415926535897931E+0,3.1415926535897931E+0]
; CHENGDU-DISABLE-OPT-NEXT:    vaddpd (%rdx), %ymm0, %ymm1
; CHENGDU-DISABLE-OPT-NEXT:    vmulpd 32(%rdx), %ymm0, %ymm0
; CHENGDU-DISABLE-OPT-NEXT:    vmovupd %ymm1, (%rdi)
; CHENGDU-DISABLE-OPT-NEXT:    vmovupd %ymm0, (%rsi)
; CHENGDU-DISABLE-OPT-NEXT:    vzeroupper
; CHENGDU-DISABLE-OPT-NEXT:    retq
;
; SUZHOU-DEFAULT-LABEL: test_broadcast_generation:
; SUZHOU-DEFAULT:       # %bb.0:
; SUZHOU-DEFAULT-NEXT:    vmovupd {{.*#+}} ymm0 = [3.1415926535897931E+0,3.1415926535897931E+0,3.1415926535897931E+0,3.1415926535897931E+0]
; SUZHOU-DEFAULT-NEXT:    vaddpd (%rdx), %ymm0, %ymm1
; SUZHOU-DEFAULT-NEXT:    vmulpd 32(%rdx), %ymm0, %ymm0
; SUZHOU-DEFAULT-NEXT:    vmovupd %ymm1, (%rdi)
; SUZHOU-DEFAULT-NEXT:    vmovupd %ymm0, (%rsi)
; SUZHOU-DEFAULT-NEXT:    vzeroupper
; SUZHOU-DEFAULT-NEXT:    retq
;
; SUZHOU-DISABLE-OPT-LABEL: test_broadcast_generation:
; SUZHOU-DISABLE-OPT:       # %bb.0:
; SUZHOU-DISABLE-OPT-NEXT:    vbroadcastsd {{.*#+}} ymm0 = [3.1415926535897931E+0,3.1415926535897931E+0,3.1415926535897931E+0,3.1415926535897931E+0]
; SUZHOU-DISABLE-OPT-NEXT:    vaddpd (%rdx), %ymm0, %ymm1
; SUZHOU-DISABLE-OPT-NEXT:    vmulpd 32(%rdx), %ymm0, %ymm0
; SUZHOU-DISABLE-OPT-NEXT:    vmovupd %ymm1, (%rdi)
; SUZHOU-DISABLE-OPT-NEXT:    vmovupd %ymm0, (%rsi)
; SUZHOU-DISABLE-OPT-NEXT:    vzeroupper
; SUZHOU-DISABLE-OPT-NEXT:    retq
  %4 = load <4 x double>, ptr %2, align 1
  %5 = getelementptr inbounds double, ptr %2, i64 4
  %6 = load <4 x double>, ptr %5, align 1
  %7 = fadd <4 x double> %4, <double 0x400921FB54442D18, double 0x400921FB54442D18, double 0x400921FB54442D18, double 0x400921FB54442D18>
  %8 = fmul <4 x double> %6, <double 0x400921FB54442D18, double 0x400921FB54442D18, double 0x400921FB54442D18, double 0x400921FB54442D18>
  store <4 x double> %7, ptr %0, align 1
  store <4 x double> %8, ptr %1, align 1
  ret void
}
